---
- name: CRON job execution
  hosts: all

  tasks:
  - name: cron job
    cron:
      name: Run test script
      minute: 30
      hour: 18
      day: 15
      month: "*"
      weekday: "*"
      user: paul
      job: /tmp/script/test.sh
