---
- name: Find and stop process
  hosts: all

  tasks:
  - name: Stopping nginx
    ignore_errors: yes
    shell: "pgrep nginx | xargs kill"
  
  - name: start the service
    service:
      name: nginx
      state: started
    
